Mic-4382/Move lint before test
ihmeuw/vivarium_research_template pull request #57
Opened 2023-09-05 23:29 UTC by albrja

## Mic-4382/Move lint before test
### Moves linting before tests in builds.
- *Category*: Other
- *JIRA issue*: [MIC-4382](https://jira.ihme.washington.edu/browse/MIC-4382)

### Changes and notes
-moves linting before tests in builds.

### Testing

2023-09-05 23:33 UTC, rmudambi approved these changes

2023-09-05 23:33 UTC, rmudambi commented on {{cookiecutter.package_name}}/.github/workflows/build.yml
> +          isort . --check -v
This should be after the `Install dependencies` step.

2023-09-05 23:35 UTC, patricktnast approved these changes

2023-09-05 23:41 UTC, rmudambi requested changes
Now it's broken. the `run` block is part of the `  - name: Install dependencies` block

2023-09-06 00:13 UTC, mattkappel commented on {{cookiecutter.package_name}}/.github/workflows/build.yml
> +          pip install black==22.3.0 isort
This choice predates this PR, but it's curious that we pin `black` here but not `isort`...

2023-09-06 00:13 UTC, mattkappel approved these changes

2023-09-06 17:38 UTC, rmudambi approved these changes

2023-09-06 18:47 UTC, merged